export const GET_FINDTRANSACTION = 'GET_FINDTRANSACTION';
export const GET_FINDTRANSACTION_SUCCESS = 'GET_FINDTRANSACTION_SUCCESS';
export const GET_FINDTRANSACTION_ERROR = 'GET_FINDTRANSACTION_ERROR';

export const getFindTransaction = (PROPERTY_CODE, CHECK_OPEN, EMPLOYEE_CODE, OUTLET_ID) => {
    return {
        type: GET_FINDTRANSACTION,
        data: { PROPERTY_CODE, CHECK_OPEN, EMPLOYEE_CODE, OUTLET_ID },
    }
}